CREATE TABLE IF NOT EXISTS quotes (
    id               TEXT PRIMARY KEY,
    customer_name    TEXT NOT NULL,
    customer_phone   TEXT,
    tech_name        TEXT,
    amount           NUMERIC(12, 2),
    status           TEXT,
    created_at       TIMESTAMPTZ,
    last_contact_at  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS events (
    event_id    UUID PRIMARY KEY,
    type        TEXT NOT NULL,
    quote_id    TEXT NOT NULL REFERENCES quotes(id),
    "timestamp" TIMESTAMPTZ NOT NULL,
    channel     TEXT CHECK (channel IN ('email', 'sms')),
    direction   TEXT CHECK (direction IN ('inbound', 'outbound'))
);

CREATE TABLE IF NOT EXISTS outbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id        TEXT NOT NULL UNIQUE,
    body            TEXT NOT NULL CHECK (btrim(body) <> ''),
    channel         TEXT NOT NULL CHECK (channel IN ('email', 'sms')),
    status          TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'sent', 'failed')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at         TIMESTAMPTZ,
    customer_phone  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sync_runs (
    id               UUID PRIMARY KEY,
    run_at           TIMESTAMPTZ NOT NULL,
    candidate_count  INTEGER NOT NULL CHECK (candidate_count >= 0),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS candidates (
    id                UUID PRIMARY KEY,
    sync_run_id       UUID NOT NULL REFERENCES sync_runs(id),
    run_at            TIMESTAMPTZ NOT NULL,
    primary_quote_id  TEXT NOT NULL REFERENCES quotes(id),
    customer_phone    TEXT NOT NULL,
    reason            TEXT NOT NULL,
    score             NUMERIC NOT NULL,
    other_quote_ids   TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[]
);

CREATE TABLE IF NOT EXISTS drafts (
    id                UUID PRIMARY KEY,
    candidate_id      UUID NOT NULL UNIQUE REFERENCES candidates(id),
    customer_phone    TEXT NOT NULL CHECK (btrim(customer_phone) <> ''),
    primary_quote_id  TEXT NOT NULL REFERENCES quotes(id),
    quote_ids         TEXT[] NOT NULL,
    body              TEXT NOT NULL CHECK (btrim(body) <> ''),
    status            TEXT NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at       TIMESTAMPTZ,
    CHECK (cardinality(quote_ids) > 0),
    CHECK (primary_quote_id = ANY(quote_ids))
);

CREATE INDEX IF NOT EXISTS idx_events_quote_id ON events(quote_id);
CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events("timestamp");
CREATE INDEX IF NOT EXISTS idx_quotes_status ON quotes(status);
CREATE INDEX IF NOT EXISTS idx_candidates_run_at ON candidates(run_at DESC);
CREATE INDEX IF NOT EXISTS idx_candidates_customer_phone
    ON candidates(customer_phone);
CREATE INDEX IF NOT EXISTS idx_drafts_status_created_at
    ON drafts(status, created_at);

CREATE OR REPLACE VIEW quote_states AS
WITH deduplicated_events AS (
    SELECT DISTINCT ON (event_id)
        event_id,
        type,
        quote_id,
        "timestamp",
        channel,
        direction
    FROM events
    ORDER BY
        event_id,
        "timestamp" ASC,
        quote_id ASC,
        type ASC,
        channel ASC NULLS FIRST,
        direction ASC NULLS FIRST
)
SELECT
    quotes.id AS quote_id,
    CASE
        WHEN quotes.status = 'open'
         AND COUNT(*) FILTER (
             WHERE deduplicated_events.type = 'quote_accepted'
         ) > 0
        THEN 'accepted'
        ELSE quotes.status
    END AS status,
    quotes.amount,
    quotes.customer_name,
    quotes.customer_phone,
    quotes.tech_name,
    quotes.created_at,
    MIN(deduplicated_events."timestamp")
        FILTER (WHERE deduplicated_events.type = 'quote_sent') AS quote_sent_at,
    MAX(deduplicated_events."timestamp")
        FILTER (WHERE deduplicated_events.type = 'quote_viewed') AS last_viewed_at,
    COUNT(DISTINCT (
        deduplicated_events."timestamp" AT TIME ZONE COALESCE(
            NULLIF(
                current_setting('follow_up_engine.business_timezone', true),
                ''
            ),
            'UTC'
        )
    )::date)
        FILTER (WHERE deduplicated_events.type = 'quote_viewed') AS view_days,
    COALESCE(
        ARRAY_AGG(
            deduplicated_events."timestamp"
            ORDER BY
                deduplicated_events."timestamp",
                deduplicated_events.event_id
        ) FILTER (WHERE deduplicated_events.type = 'quote_viewed'),
        ARRAY[]::TIMESTAMPTZ[]
    ) AS view_timestamps,
    MAX(deduplicated_events."timestamp")
        FILTER (WHERE deduplicated_events.type = 'customer_replied') AS last_replied_at,
    GREATEST(
        quotes.last_contact_at,
        MAX(deduplicated_events."timestamp") FILTER (
            WHERE deduplicated_events.type = 'message_sent'
              AND deduplicated_events.direction = 'outbound'
        )
    ) AS last_outbound_at
FROM quotes
LEFT JOIN deduplicated_events ON deduplicated_events.quote_id = quotes.id
GROUP BY
    quotes.id,
    quotes.status,
    quotes.amount,
    quotes.customer_name,
    quotes.customer_phone,
    quotes.tech_name,
    quotes.created_at,
    quotes.last_contact_at;
