CREATE TABLE IF NOT EXISTS opportunities (
    id                 TEXT PRIMARY KEY,
    contact_key        TEXT NOT NULL CHECK (btrim(contact_key) <> ''),
    contact_name       TEXT,
    contact_phone      TEXT,
    contact_email      TEXT,
    owner_name         TEXT,
    value              NUMERIC(12, 2),
    status             TEXT NOT NULL DEFAULT 'open'
                           CHECK (status IN ('open', 'won', 'lost')),
    created_at         TIMESTAMPTZ NOT NULL,
    last_contact_at    TIMESTAMPTZ,
    preferred_channel  TEXT CHECK (preferred_channel IN ('email', 'sms')),
    CHECK (
        NULLIF(btrim(contact_phone), '') IS NOT NULL
        OR NULLIF(btrim(contact_email), '') IS NOT NULL
    )
);

CREATE TABLE IF NOT EXISTS activities (
    id              TEXT PRIMARY KEY,
    type            TEXT NOT NULL,
    opportunity_id  TEXT NOT NULL REFERENCES opportunities(id),
    occurred_at     TIMESTAMPTZ NOT NULL,
    channel         TEXT CHECK (channel IN ('email', 'sms')),
    direction       TEXT CHECK (direction IN ('inbound', 'outbound'))
);

CREATE TABLE IF NOT EXISTS sync_runs (
    id               UUID PRIMARY KEY,
    run_at           TIMESTAMPTZ NOT NULL,
    candidate_count  INTEGER NOT NULL CHECK (candidate_count >= 0),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS candidates (
    id                      UUID PRIMARY KEY,
    sync_run_id             UUID NOT NULL REFERENCES sync_runs(id),
    run_at                  TIMESTAMPTZ NOT NULL,
    primary_opportunity_id  TEXT NOT NULL REFERENCES opportunities(id),
    contact_key             TEXT NOT NULL CHECK (btrim(contact_key) <> ''),
    contact_address         TEXT NOT NULL CHECK (btrim(contact_address) <> ''),
    contact_name            TEXT,
    channel                 TEXT NOT NULL CHECK (channel IN ('email', 'sms')),
    reason                  TEXT NOT NULL,
    score                   NUMERIC NOT NULL,
    other_opportunity_ids   TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[]
);

CREATE TABLE IF NOT EXISTS drafts (
    id                      UUID PRIMARY KEY,
    candidate_id            UUID NOT NULL UNIQUE REFERENCES candidates(id),
    contact_key             TEXT NOT NULL CHECK (btrim(contact_key) <> ''),
    contact_address         TEXT NOT NULL CHECK (btrim(contact_address) <> ''),
    contact_name            TEXT,
    channel                 TEXT NOT NULL CHECK (channel IN ('email', 'sms')),
    primary_opportunity_id  TEXT NOT NULL REFERENCES opportunities(id),
    opportunity_ids         TEXT[] NOT NULL,
    body                    TEXT NOT NULL CHECK (btrim(body) <> ''),
    status                  TEXT NOT NULL DEFAULT 'pending'
                                CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at             TIMESTAMPTZ,
    CHECK (cardinality(opportunity_ids) > 0),
    CHECK (primary_opportunity_id = ANY(opportunity_ids))
);

CREATE TABLE IF NOT EXISTS outbox (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id          UUID NOT NULL UNIQUE REFERENCES drafts(id),
    contact_key       TEXT NOT NULL CHECK (btrim(contact_key) <> ''),
    contact_address   TEXT NOT NULL CHECK (btrim(contact_address) <> ''),
    contact_name      TEXT,
    channel           TEXT NOT NULL CHECK (channel IN ('email', 'sms')),
    opportunity_ids   TEXT[] NOT NULL,
    body              TEXT NOT NULL CHECK (btrim(body) <> ''),
    status            TEXT NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'sent', 'failed')),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at           TIMESTAMPTZ,
    CHECK (cardinality(opportunity_ids) > 0)
);

-- Existing reservations predate explicit authorization provenance. Do not
-- retroactively claim that a human or an automatic policy approved them.
ALTER TABLE outbox ADD COLUMN IF NOT EXISTS authorization_mode
    TEXT NOT NULL DEFAULT 'legacy_unknown'
    CHECK (authorization_mode IN ('human', 'automatic', 'legacy_unknown'));

DROP INDEX IF EXISTS idx_activities_opportunity_id;
DROP INDEX IF EXISTS idx_activities_occurred_at;
DROP INDEX IF EXISTS idx_opportunities_status;
DROP INDEX IF EXISTS idx_candidates_run_at;
DROP INDEX IF EXISTS idx_candidates_contact_key;
DROP INDEX IF EXISTS idx_drafts_status_created_at;

CREATE INDEX IF NOT EXISTS idx_opportunities_contact_key
    ON opportunities(contact_key);
CREATE INDEX IF NOT EXISTS idx_activities_reduce
    ON activities(opportunity_id, occurred_at, id);
CREATE INDEX IF NOT EXISTS idx_sync_runs_latest
    ON sync_runs(run_at DESC, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_candidates_latest_run
    ON candidates(
        sync_run_id,
        score DESC,
        primary_opportunity_id,
        contact_key
    );
CREATE INDEX IF NOT EXISTS idx_outbox_contact_cooldown
    ON outbox(contact_key, created_at DESC) INCLUDE (draft_id);

CREATE OR REPLACE VIEW opportunity_states AS
WITH cutoff AS (
    SELECT COALESCE(
        NULLIF(current_setting('respawned.as_of', true), '')::TIMESTAMPTZ,
        'infinity'::TIMESTAMPTZ
    ) AS as_of
),
deduplicated AS (
    -- The primary key normally prevents duplicates. Keeping deterministic
    -- collapse here also protects projections fed by imported/staged data.
    SELECT DISTINCT ON (id)
        id,
        type,
        opportunity_id,
        occurred_at,
        channel,
        direction
    FROM activities
    ORDER BY
        id,
        occurred_at ASC,
        opportunity_id ASC,
        type ASC,
        channel ASC NULLS FIRST,
        direction ASC NULLS FIRST
),
projected AS (
    SELECT *
    FROM deduplicated
    WHERE occurred_at <= (SELECT as_of FROM cutoff)
),
aggregated AS (
    SELECT
        opportunity_id,
        (
            ARRAY_AGG(
                type ORDER BY occurred_at DESC, id DESC
            ) FILTER (WHERE type IN ('opportunity_won', 'opportunity_lost'))
        )[1] AS latest_terminal_type,
        MIN(occurred_at)
            FILTER (WHERE type = 'opportunity_created') AS activity_created_at,
        MAX(occurred_at)
            FILTER (WHERE type = 'content_viewed') AS last_viewed_at,
        COALESCE(
            ARRAY_AGG(occurred_at ORDER BY occurred_at, id)
                FILTER (WHERE type = 'content_viewed'),
            ARRAY[]::TIMESTAMPTZ[]
        ) AS view_timestamps,
        MAX(occurred_at)
            FILTER (WHERE type = 'contact_replied') AS last_replied_at,
        MAX(occurred_at) FILTER (
            WHERE type = 'message_sent' AND direction = 'outbound'
        ) AS last_message_sent_at,
        (
            ARRAY_AGG(
                channel ORDER BY occurred_at DESC, id DESC
            ) FILTER (WHERE channel IS NOT NULL)
        )[1] AS last_activity_channel,
        COALESCE(
            JSONB_AGG(
                JSONB_BUILD_OBJECT(
                    'activity_id', id,
                    'activity_type', type,
                    'occurred_at', occurred_at,
                    'channel', channel,
                    'direction', direction
                ) ORDER BY occurred_at, id
            ),
            '[]'::JSONB
        ) AS activities
    FROM projected
    GROUP BY opportunity_id
)
SELECT
    opportunities.id AS opportunity_id,
    CASE
        WHEN opportunities.status <> 'open' THEN opportunities.status
        WHEN aggregated.latest_terminal_type = 'opportunity_won' THEN 'won'
        WHEN aggregated.latest_terminal_type = 'opportunity_lost' THEN 'lost'
        ELSE opportunities.status
    END AS status,
    opportunities.value,
    opportunities.contact_key,
    opportunities.contact_name,
    opportunities.contact_phone,
    opportunities.contact_email,
    opportunities.owner_name,
    COALESCE(aggregated.activity_created_at, opportunities.created_at)
        AS created_at,
    aggregated.last_viewed_at,
    aggregated.last_replied_at,
    GREATEST(
        CASE WHEN opportunities.last_contact_at <= (SELECT as_of FROM cutoff)
            THEN opportunities.last_contact_at END,
        aggregated.last_message_sent_at
    ) AS last_outbound_at,
    COALESCE(aggregated.view_timestamps, ARRAY[]::TIMESTAMPTZ[])
        AS view_timestamps,
    COALESCE(
        opportunities.preferred_channel,
        aggregated.last_activity_channel
    ) AS preferred_channel,
    COALESCE(aggregated.activities, '[]'::JSONB) AS activities,
    aggregated.last_activity_channel
FROM opportunities
LEFT JOIN aggregated ON aggregated.opportunity_id = opportunities.id;
